apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-a
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ms-a
  template:
    metadata:
      labels:
        name: ms-a
    spec:
      containers:
        - name: ms-a
          image: mohamedbenattia/ms-a
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
       
          