apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-front
spec:
  replicas: 1
  selector:
    matchLabels:
      name: portfolio-front
  template:
    metadata:
      labels:
        name: portfolio-front
    spec:
      containers:
        - name: portfolio-front
          image: amalmissaoui9/project-portfolio
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_MSA_URL
              value: http://localhost:3001
            - name: REACT_APP_MSB_URL
              value: http://localhost:3002
          volumeMounts:
            - name:  portfolio-front-config-volume
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
              readOnly: true
      volumes:
        - name: portfolio-front-config-volume
          configMap:
            name: portfolio-front-config
         