apiVersion: v1
kind: Service
metadata:
  name: portfolio-front-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    name: portfolio-front
    version: 2.0.0
