apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-a
spec:
  replicas: {{ .Values.deployment.replicas}}
  selector:
    matchLabels:
      name: ms-a
  template:
    metadata:
      labels:
        name: ms-a
    spec:
      containers:
        - name: ms-a
          image: {{.Values.image.name}}:{{.Values.image.tag}}
          imagePullPolicy: Always
          ports:
            - containerPort: {{.Values.http.containerPort}}
       
          