apiVersion: v1
kind: Service
metadata:
  name: ms-a-svc
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.http.port }}
      protocol: TCP
      targetPort: {{ .Values.http.containerPort }}
  selector:
    name: ms-a