apiVersion: v1
kind: Service
metadata:
  name: ms-b-svc
  namespace: ms-b-ns
spec:
  type: ClusterIP
  ports:
    - port: {{.Values.http.port}}
      protocol: TCP
      targetPort: {{.Values.http.containerPort}}
  selector:
    name: ms-b