apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-b
  namespace: ms-b-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ms-b
  template:
    metadata:
      labels:
        name: ms-b
    spec:
      containers:
        - name: ms-b
          image: amalmissaoui9/project-ms-b
          imagePullPolicy: Always
          ports:
            - containerPort: 3002
          